import 'package:flutter/material.dart';

List backgroundimage=[
  {
    'Name':'Durga',
    'banner':"assets/image/durga/1.jpg",
    'image':[
      'assets/image/durga/2.jpg',
      'assets/image/durga/3.jpg',
      'assets/image/durga/4.jpg',
      'assets/image/durga/5.jpg',
      'assets/image/durga/6.jpg',
      'assets/image/durga/7.jpg',
      'assets/image/durga/8.jpg',
      'assets/image/durga/9.jpg',
      'assets/image/durga/10.jpg',
      'assets/image/durga/11.jpg',
      'assets/image/durga/12.jpg',
      'assets/image/durga/13.jpg',
      'assets/image/durga/14.jpg',
    ]

  },
  {
    'Name':'Ganesh',
    'banner':"assets/image/ganesh/1.jpg",
    'image':[
      'assets/image/ganesh/2.jpg',
      'assets/image/ganesh/3.jpg',
      'assets/image/ganesh/4.jpg',
      'assets/image/ganesh/5.jpg',
      'assets/image/ganesh/6.jpg',
      'assets/image/ganesh/7.jpg',
      'assets/image/ganesh/8.jpg',
      'assets/image/ganesh/9.jpg',
      'assets/image/ganesh/10.jpg',
      'assets/image/ganesh/11.jpg',
      'assets/image/ganesh/12.jpg',
      'assets/image/ganesh/13.jpg',
      'assets/image/ganesh/14.jpg',
    ]

  },
  {
    'Name':'Hanuman',
    'banner':"assets/image/hanuman/1.jpg",
    'image':[
      'assets/image/hanuman/2.jpg',
      'assets/image/hanuman/3.jpg',
      'assets/image/hanuman/4.jpg',
      'assets/image/hanuman/5.jpg',
      'assets/image/hanuman/6.jpg',
      'assets/image/hanuman/7.jpg',
      'assets/image/hanuman/8.jpg',
      'assets/image/hanuman/9.jpg',
      'assets/image/hanuman/10.jpg',
      'assets/image/hanuman/11.jpg',
      'assets/image/hanuman/12.jpg',
      'assets/image/hanuman/13.jpg',
      'assets/image/hanuman/14.jpg',
    ]

  },
  {
    'Name':'Kali',
    'banner':"assets/image/kali/1.jpg",
    'image':[
      'assets/image/kali/2.jpg',
      'assets/image/kali/3.jpg',
      'assets/image/kali/4.jpg',
      'assets/image/kali/5.jpg',
      'assets/image/kali/6.jpg',
      'assets/image/kali/7.jpg',
      'assets/image/kali/8.jpg',
      'assets/image/kali/9.jpg',
      'assets/image/kali/10.jpg',
      'assets/image/kali/11.jpg',
      'assets/image/kali/12.jpg',
      'assets/image/kali/13.jpg',
      'assets/image/kali/14.jpg',
    ]

  },
  {
    'Name':'Krishna',
    'banner':"assets/image/krishna/1.jpg",
    'image':[
      'assets/image/krishna/2.jpg',
      'assets/image/krishna/3.jpg',
      'assets/image/krishna/4.jpg',
      'assets/image/krishna/5.jpg',
      'assets/image/krishna/6.jpg',
      'assets/image/krishna/7.jpg',
      'assets/image/krishna/8.jpg',
      'assets/image/krishna/9.jpg',
      'assets/image/krishna/10.jpg',
      'assets/image/krishna/11.jpg',
      'assets/image/krishna/12.jpg',
      'assets/image/krishna/13.jpg',
      'assets/image/krishna/14.jpg',
    ]

  },
  {
    'Name':'Laxmi',
    'banner':"assets/image/lakshmi/1.jpg",
    'image':[
      'assets/image/lakshmi/2.jpg',
      'assets/image/lakshmi/3.jpg',
      'assets/image/lakshmi/4.jpg',
      'assets/image/lakshmi/5.jpg',
      'assets/image/lakshmi/6.jpg',
      'assets/image/lakshmi/7.jpg',
      'assets/image/lakshmi/8.jpg',
      'assets/image/lakshmi/9.jpg',
      'assets/image/lakshmi/10.jpg',
      'assets/image/lakshmi/11.jpg',
      'assets/image/lakshmi/12.jpg',
      'assets/image/lakshmi/13.jpg',
      'assets/image/lakshmi/14.jpg',
    ]

  },
  {
    'Name':'Lord Rama',
    'banner':"assets/image/ram/1.jpg",
    'image':[
      'assets/image/ram/2.jpg',
      'assets/image/ram/3.jpg',
      'assets/image/ram/4.jpg',
      'assets/image/ram/5.jpg',
      'assets/image/ram/6.jpg',
      'assets/image/ram/7.jpg',
      'assets/image/ram/8.jpg',
      'assets/image/ram/9.jpg',
      'assets/image/ram/10.jpg',
      'assets/image/ram/11.jpg',
      'assets/image/ram/12.jpg',
      'assets/image/ram/13.jpg',
      'assets/image/ram/14.jpg',
    ]

  },
  {
    'Name':'Saraswati',
    'banner':"assets/image/sarawati/1.jpg",
    'image':[
      'assets/image/sarawati/2.jpg',
      'assets/image/sarawati/3.jpg',
      'assets/image/sarawati/4.jpg',
      'assets/image/sarawati/5.jpg',
      'assets/image/sarawati/6.jpg',
      'assets/image/sarawati/7.jpg',
      'assets/image/sarawati/8.jpg',
      'assets/image/sarawati/9.jpg',
      'assets/image/sarawati/10.jpg',
      'assets/image/sarawati/11.jpg',
      'assets/image/sarawati/12.jpg',
      'assets/image/sarawati/13.jpg',
      'assets/image/sarawati/14.jpg',
    ]

  },
  {
    'Name':'Shiv',
    'banner':"assets/image/shiv/1.jpg",
    'image':[
      'assets/image/shiv/2.jpg',
      'assets/image/shiv/3.jpg',
      'assets/image/shiv/4.jpg',
      'assets/image/shiv/5.jpg',
      'assets/image/shiv/6.jpg',
      'assets/image/shiv/7.jpg',
      'assets/image/shiv/8.jpg',
      'assets/image/shiv/9.jpg',
      'assets/image/shiv/10.jpg',
      'assets/image/shiv/11.jpg',
      'assets/image/shiv/12.jpg',
      'assets/image/shiv/13.jpg',
      'assets/image/shiv/14.jpg',
    ]

  },
  {
    'Name':'Narayan',
    'banner':"assets/image/vishnu/1.jpg",
    'image':[
      'assets/image/vishnu/2.jpg',
      'assets/image/vishnu/3.jpg',
      'assets/image/vishnu/4.jpg',
      'assets/image/vishnu/5.jpg',
      'assets/image/vishnu/6.jpg',
      'assets/image/vishnu/7.jpg',
      'assets/image/vishnu/8.jpg',
      'assets/image/vishnu/9.jpg',
      'assets/image/vishnu/10.jpg',
      'assets/image/vishnu/11.jpg',
      'assets/image/vishnu/12.jpg',
      'assets/image/vishnu/13.jpg',
      'assets/image/vishnu/14.jpg',
    ]

  },
];